In [1]:
%load_ext sql

In [2]:
%env DATABASE_URL=postgresql://postgres:postgres@localhost:5432/restaurant_dw

env: DATABASE_URL=postgresql://postgres:postgres@localhost:5432/restaurant_dw

In [3]:
%config SqlMagic.autopandas = True
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [5]:
%%sql
SELECT *
FROM raw.orders
limit 100

 * postgresql://postgres:***@localhost:5432/restaurant_dw
100 rows affected.

,order_id,order_date,hour,category,item_name,price,quantity,discount,total_amount,branch,payment_method,order_type,customer_id,rating,is_weekend
0,1,2023-10-28,10,مقبلات,طحينة,17.30,2,0.0,34.59,الجيزة,Card,Delivery,168213,4,True
1,2,2024-05-25,14,مشروبات,عصير قصب,36.65,4,0.1,131.93,الإسكندرية,Wallet,Delivery,81188,4,True
2,3,2025-05-04,15,طواجن,طاجن ملوخية,96.64,3,0.0,289.91,المنصورة,Cash,Dine-in,137942,4,True
3,4,2023-07-05,14,مشروبات,عصير مانجو,23.98,3,0.0,71.95,أسيوط,Cash,Dine-in,133970,4,False
4,5,2021-12-18,19,مشروبات,عصير مانجو,19.93,5,0.1,89.71,القاهرة,Card,Dine-in,9093,4,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2022-02-06,16,طواجن,طاجن ملوخية,113.36,5,0.1,510.10,الإسكندرية,Wallet,Dine-in,115814,4,True
96,97,2021-03-12,12,مشروبات,عصير مانجو,-6.21,3,0.0,-18.62,المنصورة,Card,Takeaway,168304,4,True
97,98,2025-05-13,20,محاشي,محشي باذنجان,60.29,2,0.0,120.58,الإسكندرية,Card,Dine-in,183839,4,False
98,99,2020-12-04,16,محاشي,محشي كوسة,85.34,4,0.1,307.22,القاهرة,Wallet,Dine-in,72246,5,True
99,100,2024-01-30,11,مشويات,شيش طاووق,160.22,4,0.1,576.78,الإسكندرية,Card,Delivery,197100,3,False

In [6]:
%%sql
SELECT * 
FROM public.mart_revenue_by_branch
LIMIT 5

 * postgresql://postgres:***@localhost:5432/restaurant_dw
5 rows affected.

       branch  total_revenue  total_orders total_quantity avg_rating
0     القاهرة  1014165046.06       1785914       12463385       4.00
1      الجيزة   579692287.16       1348120        7122144       3.60
2  الإسكندرية   579207599.40       1348614        7119712       3.80
3    المنصورة   290300376.49        850192        3566833       3.40
4        طنطا   289830527.17        848147        3558195       3.30

In [7]:
%%sql
SELECT 
	 payment_method
	,COUNT(*) AS total_orders
FROM raw.orders
GROUP BY payment_method
ORDER BY total_orders

 * postgresql://postgres:***@localhost:5432/restaurant_dw
3 rows affected.

  payment_method  total_orders
0         Wallet       2221853
1           Card       3331930
2           Cash       5556217

In [8]:
%%sql
SELECT *
FROM public.mart_peak_hours
LIMIT 5

 * postgresql://postgres:***@localhost:5432/restaurant_dw
5 rows affected.

   hour  total_orders total_revenue
0    10        793312  167738909.00
1    11        792855  167977935.78
2    12        793514  167949242.38
3    13        793471  228895200.09
4    14        794412  228816312.96

In [9]:
%%sql
SELECT * 
FROM public.mart_weekend_vs_weekday

 * postgresql://postgres:***@localhost:5432/restaurant_dw
2 rows affected.

   is_weekend  total_order  total_revenue avg_order_value
0       False      6348159  1450061012.50          228.42
1        True      4761841  1448217699.10          304.13